import {
  User,
  Users,
  Briefcase,
  Megaphone,
  Palette,
  Calculator,
  Cpu,
  TrendingUp,
  Headset,
  Building2,
  GraduationCap,
  UserPlus,
  Wallet,
  Heart,
  Rocket,
  Star,
  Wrench,
  PenTool,
  Handshake,
  Phone,
  Mail,
  ClipboardList,
  Target,
  Layers,
  FileText,
  CalendarDays,
  BarChart3,
  Settings,
  Camera,
  Code,
  Lightbulb,
  type LucideIcon,
} from "lucide-react";

export const COLABORADOR_ICONS: Record<string, LucideIcon> = {
  user: User,
  users: Users,
  briefcase: Briefcase,
  megaphone: Megaphone,
  palette: Palette,
  calculator: Calculator,
  cpu: Cpu,
  "trending-up": TrendingUp,
  headset: Headset,
  building: Building2,
  graduation: GraduationCap,
  "user-plus": UserPlus,
  wallet: Wallet,
  heart: Heart,
  rocket: Rocket,
  star: Star,
  wrench: Wrench,
  "pen-tool": PenTool,
  handshake: Handshake,
  phone: Phone,
  mail: Mail,
  clipboard: ClipboardList,
  target: Target,
  layers: Layers,
  "file-text": FileText,
  calendar: CalendarDays,
  chart: BarChart3,
  settings: Settings,
  camera: Camera,
  code: Code,
  lightbulb: Lightbulb,
};

export const ICON_KEYS = Object.keys(COLABORADOR_ICONS);

export function getColaboradorIcon(key: string | null | undefined): LucideIcon {
  return (key && COLABORADOR_ICONS[key]) || User;
}

export const COLABORADOR_COLORS = [
  "#a855f7",
  "#ec4899",
  "#f59e0b",
  "#22c55e",
  "#3b82f6",
  "#36afc0",
  "#ef4444",
  "#14b8a6",
  "#8b5cf6",
  "#f97316",
  "#0ea5e9",
  "#84cc16",
];
